export const PRESSURE_CHANGE = 'SENSOR/PRESSURE_CHANGE';
export const ALTITUDE_CHANGE = 'SENSOR/ALTITUDE_CHANGE';
export const GPS_CHANGE      = 'SENSOR/GPS_CHANGE';
export const CLEAR_VALUES    = 'SENSOR/CLEAR_VALUES';